# Generated by Django 4.2.7 on 2025-12-29 00:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("categories", "0001_initial"),
        ("locations", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Item",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=200, verbose_name="Название вещи"),
                ),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
                (
                    "purchase_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Дата покупки"
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Цена",
                    ),
                ),
                (
                    "photo",
                    models.ImageField(
                        blank=True, null=True, upload_to="items/", verbose_name="Фото"
                    ),
                ),
                (
                    "qr_code",
                    models.ImageField(
                        blank=True, upload_to="qrcodes/", verbose_name="QR-код"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создано"),
                ),
                (
                    "category",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="categories.category",
                        verbose_name="Категория",
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="locations.location",
                        verbose_name="Место хранения",
                    ),
                ),
            ],
            options={
                "verbose_name": "Вещь",
                "verbose_name_plural": "Вещи",
                "ordering": ["-created_at"],
            },
        ),
    ]
